// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvXAaeiXcEyykEQqriFCf9xMyxClht9Y0',
    appId: '1:516238564892:web:c595214ef4333229ee89d9',
    messagingSenderId: '516238564892',
    projectId: 'flutter-test-45793',
    authDomain: 'flutter-test-45793.firebaseapp.com',
    storageBucket: 'flutter-test-45793.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHehT1R8CmxH5LDkIGSOE1ygCh1PCY-yg',
    appId: '1:516238564892:android:263a857695b65263ee89d9',
    messagingSenderId: '516238564892',
    projectId: 'flutter-test-45793',
    storageBucket: 'flutter-test-45793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyojfFn-Z_CNuObthTZ80iIuv_iVEtuUo',
    appId: '1:516238564892:ios:2dccd68a664191a7ee89d9',
    messagingSenderId: '516238564892',
    projectId: 'flutter-test-45793',
    storageBucket: 'flutter-test-45793.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyojfFn-Z_CNuObthTZ80iIuv_iVEtuUo',
    appId: '1:516238564892:ios:2dccd68a664191a7ee89d9',
    messagingSenderId: '516238564892',
    projectId: 'flutter-test-45793',
    storageBucket: 'flutter-test-45793.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvXAaeiXcEyykEQqriFCf9xMyxClht9Y0',
    appId: '1:516238564892:web:fa0945b9956f7d88ee89d9',
    messagingSenderId: '516238564892',
    projectId: 'flutter-test-45793',
    authDomain: 'flutter-test-45793.firebaseapp.com',
    storageBucket: 'flutter-test-45793.firebasestorage.app',
  );
}
